# Generated by Django 4.2.16 on 2024-10-26 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('designationEcole', models.CharField(max_length=150)),
                ('arreteMin', models.CharField(max_length=100)),
                ('adresse', models.TextField()),
                ('telephone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('typesEcole', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('promoteur', models.CharField(max_length=100)),
                ('biographie', models.TextField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MasomoClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designationClasse', models.CharField(max_length=150)),
                ('etablissement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API_Masomo.etablissement')),
            ],
        ),
        migrations.CreateModel(
            name='MasomoSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designationSection', models.CharField(max_length=150)),
                ('classeMasomo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API_Masomo.masomoclasse')),
            ],
        ),
        migrations.CreateModel(
            name='MasomoOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designationOption', models.CharField(max_length=200)),
                ('sectionMasomo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API_Masomo.masomosection')),
            ],
        ),
    ]
